# -*- coding: utf-8 -*-
"""Personal Expense

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1peCRE8Uvkgq9KCXEsqBeBQPE8mqRa34D
"""

import pandas as pd

pip install pandas

df = pd.read_csv("/content/budget_data.csv")

print(df.head())

print(df.info())

print(df.isnull().sum())

print(df.describe())

print(df.columns)

df['date'] = pd.to_datetime(df['date'])

import matplotlib.pyplot as plt

category_expense = df.groupby('category')['amount'].sum()
print(category_expense)

category_expense.plot.pie(autopct='%1.1f%%', figsize=(6,6))
plt.title("Expenses by Category")
plt.show()

df['Month'] = df['date'].dt.month
monthly_expense = df.groupby('Month')['amount'].sum()
monthly_expense.plot(kind='bar', figsize=(8,5))
plt.title("Monthly Spending Trend")
plt.show()

df['date'] = pd.to_datetime(df['date'])

df['YearMonth'] = df['date'].dt.to_period('M')

monthly_expense = df.groupby('YearMonth')['amount'].sum().reset_index()
print(monthly_expense)

from sklearn.linear_model import LinearRegression
import numpy as np

monthly_expense['Month_Num'] = np.arange(len(monthly_expense))

X = monthly_expense[['Month_Num']]
y = monthly_expense['amount']

model = LinearRegression()
model.fit(X, y)

next_month_num = [[X['Month_Num'].max() + 1]]
predicted_next_month = model.predict(next_month_num)
print(f"Predicted expense for next month: {predicted_next_month[0]:.2f}")

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

le = LabelEncoder()
df['Payment_Mode_encoded'] = le.fit_transform(df['Payment_Mode'])

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

df = pd.read_csv("/content/budget_data.csv")

df['date'] = pd.to_datetime(df['date'])

df['YearMonth'] = df['date'].dt.to_period('M')

df['YearMonth'] = df['date'].dt.to_period('M')

monthly_expense = df.groupby('YearMonth')['amount'].sum().reset_index()

print(df.head())

monthly_expense['Month_Num'] = np.arange(len(monthly_expense))
X = monthly_expense[['Month_Num']]
y = monthly_expense['amount']

model = LinearRegression()
model.fit(X, y)

next_month_num = [[X['Month_Num'].max() + 1]]
predicted_next_month = model.predict(next_month_num)
print(f"Predicted total expense for next month: {predicted_next_month[0]:.2f}")

monthly_expense = df.groupby('YearMonth')['amount'].sum().reset_index()
print(monthly_expense)

monthly_expense['Month_Num'] = np.arange(len(monthly_expense))

from sklearn.linear_model import LinearRegression

X = monthly_expense[['Month_Num']]
y = monthly_expense['amount']

model = LinearRegression()
model.fit(X, y)

next_month_num = [[X['Month_Num'].max() + 1]]
predicted_next_month = model.predict(next_month_num)
print(f"Predicted total expense for next month: {predicted_next_month[0]:.2f}")

import matplotlib.pyplot as plt

monthly_expense.set_index('YearMonth', inplace=True)
monthly_expense['amount'].plot(kind='line', marker='o', figsize=(8,5))
plt.title("Monthly Spending Trend")
plt.ylabel("Amount")
plt.show()

from google.colab import files

# Example: download the CSV
files.download('/content/budget_data.csv')

# Example: download Python script
files.download('expense_tracker.py')